### ISSUE TITLE
[StaticWebsite]: CNAME is already associated with a different resource

### ISSUE THREAD

**Issue by michaelfecher** [jogold/cloudstructs#169]
The following basic example fails for me when running `cdk deploy`:

```
const accountDomain = 'dev.fubar.com';
const importedHostedZone = HostedZone.fromHostedZoneAttributes(this, 'ImportedHostedZone', {
  hostedZoneId: importedHostedZoneId,
  zoneName: accountDomain 
});
const staticWebsite = new cloudstructs.StaticWebsite(this, 'StaticWebsite', {
    domainName: accountDomain,
    hostedZone: importedHostedZone,
    backendConfiguration: {
      baseUrl: accountDomain
    }
  });
```

The HostedZone for 'dev.fubar.com' has no CNAME record, only the NS and the SOA. 
There are no other CloudFront distributions in this account.

3:37:24 PM | CREATE_FAILED        | AWS::CloudFront::Distribution                   | StaticWebsite319123A6
Resource handler returned message: "Invalid request provided: One or more of the CNAMEs you provided are already associated with a different resource. (Service: CloudFront, Status Code: 409, Request ID: 04c3eb61-4314-43e1-b511-8979a4bce421)"

**Comment by jogold** [comment]
Hi @michaelfecher 

Can you check if the CNAME is already referenced in another **CloudFront** distribution?

**Comment by michaelfecher** [comment]
There are no other CloudFront distributions, unfortunately.

**Comment by michaelfecher** [comment]
I manually created the CloudFront distro, the ACM cert in us-east-1, and the corresponding CNAME record for 'dev.fubar.com' without the `StaticWebsite` construct.
It works without any CNAME conflicts.

**Comment by jogold** [comment]
It's not about the CNAME in Route53 but the alias/alternate domain name used in the CloudFront distribution.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html

**Comment by jogold** [comment]
By default the construct creates a redirect from `fubar.com` to `dev.fubar.com` (see README). Is `fubar.com` maybe already used in a distribution?

If you don't want this behavior, pass `[]` to `redirects`.

**Comment by michaelfecher** [comment]
Thank you!
When passing `[]` to redirects, it's deployable.
I completely misunderstood the doc of the argument and left it out as you can see in the original code snippet.

```
@default
the domain name of the hosted zone
```
I understood, that it skips the redirection and uses internally the hostedZone domain if not passed.
In my case, the `hostedZone` domain IS the `domainName`.
So it's trying as you wrote, to create two distributions for one domain, if I got you correctly.
This raises the error then.

**Comment by jogold** [comment]
Can you try with `v0.4.22`?
