### ISSUE TITLE
Deployment detail

### ISSUE THREAD

**Issue by jonathan-kosgei** [jogold/cloudstructs#200]
Quick question, do I need to deploy this once per region or once per account?

**Comment by jogold** [comment]
Assuming you're talking about the `ToolkitCleaner`, you need one per account+region (= bootstrapped environnement).

**Comment by jogold** [comment]
@jonathan-kosgei does this answer your question?

**Comment by jonathan-kosgei** [comment]
It does, thanks for making this!
