### ISSUE TITLE
Should the trigger re-run the state machine if the state machine has been modified?

### ISSUE THREAD

**Issue by phitoduck** [jogold/cloudstructs#203]
Hi there, thanks for this awesome library!

I think the `StateMachineCustomResourceProvider` may save me 2-3 days of work figuring out how to make a custom resource that executes a state machine.

One thing my team and I noticed: it seems that if we do a `cdk deploy` wherein we added new tasks to our state machine, the trigger does not actually execute our state machine. 

Better said: If the `cdk deploy` is creating the state machine from scratch, it gets triggered. If the `cdk deploy` is adding/modifying tasks in an existing state machine's definition, it doesn't get triggered.

Is this the desired behavior? If so, does a workaround come to mind we could use to achieve that result?

Here's our usage of the resource:

```python
def trigger_state_machine(self, state_machine: sfn.StateMachine) -> CustomResource:
    """
    Execute the ETL state machine.

    Find documentation on the ``cloudstructs.StateMachineCustomResourceProvider``
    here: https://github.com/jogold/cloudstructs/tree/18116c10466b3cf7c7a8e1acde1eb5c22dfb1b64/src/state-machine-cr-provider
    """
    state_machine_trigger_provider = StateMachineCustomResourceProvider(
        self,
        self.namer("trigger-etl-state-machine-provider"),
        # due to this dependency, should it be the case that the provider/custom resource should
        # cause the state machine trigger to execute the state machine EXACTLY
        # when we've modified the state machine?
        state_machine=state_machine,
    )

    # creation of this resource will actually execute the ETL job for the customer ✨
    state_machine_trigger = CustomResource(
        self,
        self.namer("trigger-etl-state-machine"),
        service_token=state_machine_trigger_provider.service_token,
        # these could be inputs to the resource
        properties={},
    )

    return state_machine_trigger
```

**Comment by jogold** [comment]
Hi @phitoduck 

This is the expected behavior, in line with what happens with a "normal" Lambda backed custom resource. The custom resource like any other CloudFormation resources only gets updated when its properties change.

If you want your Custom Resource to run on every deploy you need to change its properties so CloudFormation triggers an UPDATE event. One way to achieve this is to pass a timestamp or a version to the properties of your Custom Resource.

**Comment by jogold** [comment]
Closing for now, feel free to reopen if not clear.
