### ISSUE TITLE
Vulnerability through bundled dependency got > cacheable-request > http-cache-semantics

### ISSUE THREAD

**Issue by cuzzlor** [jogold/cloudstructs#214]
There is a [vulnerability](https://github.com/advisories/GHSA-rc47-6667-2j5j) in http-cache-semantics.

Having a bundled dep seemingly makes it impossible to override the vulnerable http-cache-semantics package version (I could be wrong, but I can't see a way).

Is it possible to update deps to avoid the vulnerability, or change to not use bundled packages (excuse me if I have some assumptions wrong, I wasn't aware of `bundled` dependencies until this came up)?

`npm audit`
![image](https://user-images.githubusercontent.com/5326367/216237611-f887e951-199f-40e8-8119-e11c012e4525.png)

`npm why http-cache-semantics`
![image](https://user-images.githubusercontent.com/5326367/216237659-ba389702-aef2-4082-a406-7669763cedf8.png)

Thanks!

**Comment by jogold** [comment]
Fixed with #213.

**Comment by jogold** [comment]
FYI with [`jsii`](https://github.com/aws/jsii) we must use bundled deps unfortunately...
