### ISSUE TITLE
Missing ListStacks permission

### ISSUE THREAD

**Issue by mdesanti** [jogold/cloudstructs#215]
Hello!

I just deployed this stack into my App Stack and the Step Functions is failing with the following error:

```
is not authorized to perform: cloudformation:ListStacks on resource: arn:aws:cloudformation:us-east-1:XXX:stack/*/* because no identity-based policy allows the cloudformation:ListStacks action
```

If manually added the permisson and it seems to work propertly. Any idea if I am doing something wrong? If not, is it ok to send a PR with this fix?

**Comment by jogold** [comment]
Hi @mdesanti,

Which construct are you using and were do you see this error? During deploy or at runtime?

**Comment by mdesanti** [comment]
I'm sorry for the lack of detail. 

I'm using the ToolkitCleaner and it's a runtime error in the Get Stack Names function
