### ISSUE TITLE
ToolkitCleaner is using deprecated API

### ISSUE THREAD

**Issue by mbp** [jogold/cloudstructs#239]
When using the `ToolkitCleaner` construct:

```
[WARNING] aws-cdk-lib.aws_stepfunctions.StateMachineProps#definition is deprecated.
  use definitionBody: DefinitionBody.fromChainable()
  This API will be removed in the next major release.
```

**Comment by jogold** [comment]
Hi @mbp,

Thank for reporting this but I cannot change this for now since it would require all users of this construct to update to `aws-cdk-lib` v2.85.0.

**Comment by mbp** [comment]
Hi @jogold, thanks for your prompt response.

In our project, we have a policy of not using deprecated APIs, so we can be prepared for future CDK versions. Our build will fail, if using deprecated APIs. So it makes it difficult for us to upgrade to newer versions, while packages like `cloudstructs` is using deprecated APIs.

But I totally understand your reasoning. Do you only expect to migrate from deprecated APIs when cdk v3 comes out, or could it be sooner?

**Comment by jogold** [comment]
> But I totally understand your reasoning. Do you only expect to migrate from deprecated APIs when cdk v3 comes out, or could it be sooner?

It could be sooner but I haven't decided yet.

I will leave this issue open in the meantime.

**Comment by Mahdi-Malekan** [comment]
Any news on this?

**Comment by jogold** [comment]
> Any news on this?

Not yet, sorry.
