### ISSUE TITLE
Be more specific about locating hashes

### ISSUE THREAD

**Issue by wz2b** [jogold/cloudstructs#241]
https://github.com/jogold/cloudstructs/blob/02958bf8058944b17f093ad502cd84c5ebe5085d/src/toolkit-cleaner/extract-template-hashes.lambda.ts#L14

Do you think it would be safe to find the assets from the cdk metadata i.e. modify our pattern to be:

```
(/asset.([a-f0-9]{64})/g);
```

I'm a little concerned this pattern is too generic and will pick out other guid looking things that just happen to be the wrong length.  It doesn't matter a _lot_ since other random guids probably won't be files in the bucket.  But this seems a little coarse.

That said, I tried to rewrite using an actual template parser and it was rough.  The CfnParser in CDK wasn't really meant to be used externally and I can't get it to work.  So I'm not sure I have a better alternative (yet).

**Comment by jogold** [comment]
Hey @wz2b,

I guess we can do that. Do you want to open a PR for this?

**Comment by jogold** [comment]
Closing for now.
