### ISSUE TITLE
Update @slack/web-api to 7.3.4 to remove Axios high severity vulnerability

### ISSUE THREAD

**Issue by Saku75** [jogold/cloudstructs#279]
Currently the outdated @slack/web-api dependency is creating a high severity vulnerability due to Axios.

In @slack/web-api [7.3.4](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Fweb-api%407.3.4), the Axios version was bumped to 1.7.4 to fix this issue.

What are the requirements for this package to update the @slack/web-api dependency?

**Comment by jogold** [comment]
Hi @Saku75 

Will try to fix this this week.
